spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fornecedor
    username: root
    password: itfprod
    driver-class-name: org.mariadb.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
  ddl-auto: update
